# -*- coding: utf-8 -*-
"""BP about AI trend in healthcare

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I9aZCXYZrEQjpS6JTtVAugqQMCYjGwCE
"""

pip install crewai langchain openai

pip install langchain langchain-community langchain-openai

pip install -U langchain langchain-openai

from langchain_openai import OpenAI

from crewai import Agent, Task, Crew
from langchain.llms import OpenAI

# Set your OpenAI API key in your environment or use directly
import os
os.environ["OPENAI_API_KEY"] = "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"
llm = OpenAI(temperature=0.7)

# Agent 1: Content Strategist
content_strategist = Agent(
    role='Content Strategist',
    goal='Define the target audience and focus topics for the blog post',
    backstory="An expert in digital content marketing and audience engagement.",
    verbose=True,
    llm=llm
)

# Agent 2: Researcher
researcher = Agent(
    role='Research Specialist',
    goal='Find the latest AI trends in the healthcare industry',
    backstory="An analyst who keeps track of the latest developments in AI and medicine.",
    verbose=True,
    llm=llm
)

# Agent 3: Writer
writer = Agent(
    role='Technical Writer',
    goal='Write an engaging blog post on AI in healthcare using the provided research',
    backstory="A professional blog writer skilled in translating complex topics into digestible articles.",
    verbose=True,
    llm=llm
)

# Agent 4: Editor
editor = Agent(
    role='Content Editor',
    goal='Edit the article for grammar, clarity, and tone',
    backstory="A senior editor with a strong eye for detail and style.",
    verbose=True,
    llm=llm
)

task1 = Task(
    description='Identify the ideal target audience and outline the key focus areas for an article about AI trends in healthcare.',
    agent=content_strategist,
    expected_output='A list of audience types and 3-5 key topics or questions the article should cover.'
)
task2 = Task(
    description='Research and summarize recent AI advancements in the healthcare sector, including use cases and statistics.',
    agent=researcher,
    depends_on=[task1],
    expected_output='A concise report summarizing at least 3 major recent advancements with relevant data or examples.'
)

task3 = Task(
    description='Using the strategy and research, write a 500-word blog post on AI in healthcare.',
    agent=writer,
    depends_on=[task2],
    expected_output='A well-structured blog post of approximately 500 words on AI trends in healthcare.'
)

task4 = Task(
    description='Proofread and edit the blog post for tone, clarity, and grammar.',
    agent=editor,
    depends_on=[task3],
    expected_output='A polished and edited version of the blog post, ready for publication.'
)

# Define the crew and run the workflow
crew = Crew(
    agents=[content_strategist, researcher, writer, editor],
    tasks=[task1, task2, task3, task4],
    verbose=True
)

result = crew.kickoff()
print("\n📝 Final Output:\n", result)

